# Generated by Django 5.0.1 on 2024-01-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_model',
            old_name='location_Details',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='job_model',
            name='Division',
        ),
    ]
