# Generated by Django 5.0.1 on 2024-01-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0003_jobapplymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('careerImage', models.ImageField(blank=True, null=True, upload_to='media/career')),
            ],
        ),
    ]
