# Generated by Django 5.0.1 on 2024-01-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0004_careermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_model',
            name='job_image',
            field=models.ImageField(null=True, upload_to='job_image/'),
        ),
    ]
